import { useState } from 'react';
import {
  AlertCircle, ArrowDownToLine, ArrowRight, BookOpen, Check, CheckCircle2,
  ChevronRight, ClipboardCheck, Clock3, FileText, GitBranch, Layers3,
  Search, ShieldCheck, Sparkles, Target, Wrench,
} from 'lucide-react';
import { canClose, DISPOSITION_NAMES, reviewDocuments } from './domain.ts';
import type { CaseState, Disposition, DocumentState, ReviewDocument, Task } from './domain.ts';

const dispositionDescriptions: Partial<Record<Disposition, string>> = {
  accept: 'Accept the documented deviation within the applicable limits.',
  repair: 'Restore serviceability using an applicable repair instruction.',
  rework: 'Bring the item back to its original design requirements.',
  exchange: 'Exchange the affected item for a conforming unit.',
  reject: 'Hold or return the item; no irreversible disposal.',
  scrap: 'Permanently withdraw the item with recorded traceability.',
  engineering: 'Obtain an opinion before a final disposition is decided.',
};

type AssessmentProps = {
  c: CaseState; onAssess: () => void; onReview: (d?: Disposition) => void;
  onDocument: (d: ReviewDocument) => void; onRecord: () => void;
  onDocumentState: (s: DocumentState) => void; onContinue: () => void;
};

export function AssessmentWorkspace({ c, onAssess, onReview, onDocument, onRecord, onDocumentState, onContinue }: AssessmentProps) {
  const [tab, setTab] = useState<'criteria' | 'documents' | 'options'>('criteria');
  const a = c.assessment;
  const docs = a?.documents ?? reviewDocuments(c.fields, c.categoryConfirmed, c.documentState ?? 'aligned');
  const gaps = a?.criteria.filter(r => r.status !== 'pass').length ?? 0;
  const locked = Boolean(c.disposition);
  return <section className="phase-workbench card" aria-label="Assessment workspace">
    <div className="card-heading"><div className="card-heading-title"><Target size={17} /><h2>Assessment workspace</h2></div><span className={`badge ${a ? 'blue' : ''}`}>{locked ? 'Decision recorded' : a ? 'Ready for review' : 'To assess'}</span></div>
    <div className="workbench-scroll">
      <div className="phase-case-strip"><div><span className="section-eyebrow">{c.id}</span><strong>{c.fields.program} <span>· MSN {c.fields.msn}</span></strong><small>{c.fields.part || 'Part not identified'} · {c.fields.zone}</small></div><button className="button small" onClick={onRecord}><FileText size={13} />Case record</button></div>
      <div className="workbench-heading"><span className="phase-eyebrow"><Sparkles size={13} />MULTI-CRITERIA DOCUMENT REVIEW</span><h3>One decision. Every criterion in view.</h3><p>Correlate the captured facts with the DAC, process instructions and quality procedures.</p></div>
      <div className="assessment-metrics"><div><BookOpen size={15} /><strong>{docs.length}</strong><span>{a ? 'Documents reviewed' : 'Candidate documents'}</span></div><div><Layers3 size={15} /><strong>{a?.criteria.length ?? '—'}</strong><span>Criteria evaluated</span></div><div className={gaps ? 'has-gap' : ''}><AlertCircle size={15} /><strong>{a ? gaps : '—'}</strong><span>Points to address</span></div></div>
      <div className="document-variation"><label htmlFor="document-set">Demo document set</label><select id="document-set" value={c.documentState ?? 'aligned'} disabled={locked} onChange={e => onDocumentState(e.target.value as DocumentState)}><option value="aligned">Aligned revisions</option><option value="missing">Instruction unavailable</option><option value="conflict">DAC revision conflict</option></select></div>
      <div className="workbench-tabs" role="tablist" aria-label="Assessment views">{(['criteria', 'documents', 'options'] as const).map((t, i) => <button key={t} id={`assessment-tab-${t}`} aria-controls={`assessment-panel-${t}`} role="tab" aria-selected={tab === t} tabIndex={tab === t ? 0 : -1} className={tab === t ? 'selected' : ''} onClick={() => setTab(t)} onKeyDown={e => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); const tabs = ['criteria', 'documents', 'options'] as const; const next = tabs[(i + (e.key === 'ArrowRight' ? 1 : 2)) % 3]; setTab(next); document.getElementById(`assessment-tab-${next}`)?.focus(); } }}>{t === 'criteria' ? 'Criteria matrix' : t === 'documents' ? 'Source documents' : 'Disposition options'}{t === 'documents' && <span>{docs.length}</span>}</button>)}</div>
      <div role="tabpanel" aria-labelledby={`assessment-tab-${tab}`} id={`assessment-panel-${tab}`}>
        {tab === 'criteria' && (a ? <div className="criteria-matrix"><div className="matrix-column-labels"><span>Criterion & observed facts</span><span>Result / reference</span></div>{a.criteria.map(r => <div className={`criterion-row ${r.status}`} key={r.id}><span className="criterion-symbol">{r.status === 'pass' ? <Check size={13} /> : r.status === 'fail' ? <AlertCircle size={13} /> : r.status === 'review' ? <GitBranch size={13} /> : <Search size={13} />}</span><div className="criterion-facts"><strong>{r.title}</strong><span>{r.observed}</span><small>{r.rule}</small></div><div className="criterion-result"><span className={`criterion-status ${r.status}`}>{r.status === 'pass' ? 'Satisfied' : r.status === 'fail' ? 'Not satisfied' : r.status === 'review' ? 'Review needed' : 'Evidence needed'}</span><button onClick={() => { const d = docs.find(d => d.id === r.source); if (d) onDocument(d); }}>{r.source}<ArrowRight size={10} /></button><small>{r.section}</small></div></div>)}<p className="matrix-note">A failed acceptance criterion can still permit repair or rework if a separate instruction supports it. Missing or conflicting evidence requires engineering review.</p></div> : <div className="assessment-pending"><span className="pending-icon"><Search size={25} strokeWidth={1.5} /></span><h4>Bring the evidence together.</h4><p>Run the review to see which criteria are satisfied, which acceptance limits are exceeded, and which points need an engineering opinion.</p><div className="review-sequence"><span><BookOpen size={13} />Match documents</span><ChevronRight size={12} /><span><Layers3 size={13} />Evaluate criteria</span><ChevronRight size={12} /><span><GitBranch size={13} />Recommend next step</span></div>{!c.categoryConfirmed && <div className="note amber"><AlertCircle size={15} /><span>Confirm the defect type in the case record before assessing.</span></div>}</div>)}
        {tab === 'documents' && <div className="assessment-documents">{docs.map(d => <button key={d.id} className={`assessment-document ${d.status}`} onClick={() => onDocument(d)}><span className="document-type">{d.kind === 'DAC' ? <Target size={19} /> : d.kind === 'Instruction' ? <Wrench size={19} /> : d.kind === 'Inspection' ? <ClipboardCheck size={19} /> : <ShieldCheck size={19} />}</span><div><span className="section-eyebrow">{d.kind}</span><strong>{d.id} <small>Rev. {d.revision}</small></strong><p>{d.title}</p><small>{d.scope}</small></div><span className={`badge ${d.status === 'consulted' ? 'green' : 'amber'}`}>{d.status === 'consulted' ? a ? 'Consulted' : 'Available' : d.status === 'conflict' ? 'Conflict' : 'Missing'}</span><ChevronRight size={14} /></button>)}<p className="matrix-note">Fictional, controlled demo documents. Historical QMS examples support context and do not override a requirement.</p></div>}
        {tab === 'options' && <div className="disposition-grid">{(['repair', 'rework', 'exchange', 'reject', 'scrap', 'accept', 'engineering'] as Disposition[]).map(d => { const available = Boolean(a?.options.includes(d)); return <button key={d} className={`disposition-tile ${a?.recommended === d ? 'recommended' : ''}`} disabled={!available || locked} title={available ? 'Review this disposition or action' : 'Not supported by the current assessment'} onClick={() => onReview(d)}><div><strong>{DISPOSITION_NAMES[d]}</strong>{a?.recommended === d && <span className="badge green">Recommended</span>}</div><p>{dispositionDescriptions[d]}</p><span>{available ? d === 'engineering' ? 'Prepare a referral' : 'Review this option' : a ? 'Not supported for this case' : 'Assess to establish eligibility'}{available && <ArrowRight size={12} />}</span></button>; })}</div>}
      </div>
      {a && <div className={`recommendation-summary ${a.recommended === 'engineering' ? 'referral' : ''}`}><div className="recommendation-icon">{a.recommended === 'engineering' ? <GitBranch size={21} /> : <Sparkles size={21} />}</div><div><span className="section-eyebrow">{a.recommended === 'engineering' ? 'NEXT ACTION · NOT A FINAL DISPOSITION' : 'DOCUMENT-BASED RECOMMENDATION'}</span><h3>{a.title}</h3><strong>{a.recommended === 'engineering' ? 'Request an engineering opinion' : DISPOSITION_NAMES[a.recommended]}</strong><p>{a.explanation}</p><div className="recommendation-citations">{docs.filter(d => d.status === 'consulted').map(d => <button key={d.id} onClick={() => onDocument(d)}><FileText size={11} />{d.id}</button>)}</div></div></div>}
    </div>
    <div className="workbench-footer"><span><ShieldCheck size={13} />{locked ? 'Decision retained in the case history.' : 'Your review determines the next step.'}</span><div>{locked ? <button className="button primary" onClick={onContinue}>Go to execution <ArrowRight size={14} /></button> : <><button className={`button ${a ? '' : 'primary'}`} onClick={onAssess}><Search size={14} />{a ? 'Re-run assessment' : 'Assess the case'}</button>{a && <button className="button primary" onClick={() => onReview()}>Review disposition <ArrowRight size={14} /></button>}</>}</div></div>
  </section>;
}

type ExecutionProps = { c: CaseState; onRecord: () => void; onTask: (task: Task) => void; onClose: () => void; onExport: () => void; onDocument: (d: ReviewDocument) => void };

export function ExecutionWorkspace({ c, onRecord, onTask, onClose, onExport, onDocument }: ExecutionProps) {
  const completed = c.tasks.filter(t => t.done).length, next = c.tasks.find(t => !t.done);
  const instruction = c.assessment?.documents.find(d => d.kind === 'Instruction');
  const referral = c.disposition === 'engineering';
  return <section className="phase-workbench execution-workspace card" aria-label="Execution workspace"><div className="card-heading"><div className="card-heading-title"><ClipboardCheck size={17} /><h2>Execution workspace</h2></div><span className={`badge ${c.closed ? 'green' : referral ? 'amber' : 'blue'}`}>{c.closed ? 'Closed' : referral ? 'Awaiting engineering' : 'In progress'}</span></div>
    <div className="workbench-scroll"><div className="phase-case-strip"><div><span className="section-eyebrow">{c.id}</span><strong>{c.fields.program} <span>· MSN {c.fields.msn}</span></strong><small>{c.fields.part || 'Part not identified'} · {c.fields.zone}</small></div><button className="button small" onClick={onRecord}><FileText size={13} />Case record</button></div>
      <div className="workbench-heading"><span className="phase-eyebrow"><ClipboardCheck size={13} />{referral ? 'ENGINEERING REFERRAL' : 'APPROVED DISPOSITION · EXECUTION'}</span><h3>{referral ? 'Get the opinion. Then decide.' : c.closed ? 'A resolution you can trace.' : 'Turn the decision into action.'}</h3><p>{referral ? 'Track the request and record an engineering-approved disposition before executing it.' : 'Follow the responsible teams, work orders and inspection evidence through to closure.'}</p></div>
      <div className="execution-metrics"><div><span>Action progress</span><strong>{completed}<small> / {c.tasks.length}</small></strong><div className="execution-progress"><i style={{ width: `${completed / Math.max(1, c.tasks.length) * 100}%` }} /></div></div><div><span>Next responsible team</span><strong className="metric-team">{next?.owner ?? 'Complete'}</strong><small>{next ? 'Action ready to progress' : 'All actions recorded'}</small></div><div><span>Final inspection</span><strong className="metric-team">{c.finalCheck ? 'Recorded' : 'Pending'}</strong><small>{referral ? 'Plan to be defined' : 'Required before closure'}</small></div></div>
      <div className="approved-decision"><span className="decision-glyph">{referral ? <GitBranch size={19} /> : <CheckCircle2 size={19} />}</span><div><span className="section-eyebrow">{referral ? 'REQUEST IN PROGRESS' : 'RECORDED DISPOSITION'}</span><h3>{c.disposition ? DISPOSITION_NAMES[c.disposition] : 'Pending'}</h3><p>{c.decisionReason}</p><span className="decision-owner">{referral ? 'Requested' : 'Reviewed'} by Marie Laurent · simulated workflow</span></div>{instruction && !referral && (c.disposition === 'repair' || c.disposition === 'rework') && <button className="text-button" onClick={() => onDocument(instruction)}><BookOpen size={13} />{instruction.id}</button>}</div>
      <div className="execution-plan-heading"><div><h3>Resolution plan</h3><p>Actions run in sequence; every update is recorded.</p></div><span className="badge">{c.closed ? 'Complete' : 'Simulation'}</span></div>
      <div className="execution-task-list">{c.tasks.map((task, i) => { const available = !c.closed && !task.done && c.tasks.slice(0, i).every(t => t.done); return <div className={`execution-task ${task.done ? 'complete' : available ? 'current' : ''}`} key={task.id}><span className="execution-task-marker">{task.done ? <Check size={17} /> : String(i + 1).padStart(2, '0')}</span><div className="execution-task-detail"><span className="section-eyebrow">{task.done ? 'COMPLETED' : available ? 'NEXT ACTION' : 'WAITING FOR PREVIOUS ACTION'}</span><strong>{task.title}</strong><span className="execution-task-team">{task.owner}{task.id === 'order' && task.done ? ` · WO-DEMO-${c.id.slice(-6)}` : ''}</span></div><button className={`button small ${available ? 'primary' : ''}`} disabled={!available} onClick={() => onTask(task)}>{task.done ? 'Done' : task.kind === 'inspection' ? 'Record inspection' : task.kind === 'opinion' ? 'Record opinion' : 'Mark complete'}</button></div>; })}</div>
      <div className="execution-bottom-grid"><div className={`verification-gate ${c.finalCheck ? 'verified' : ''}`}><ClipboardCheck size={21} /><span className="section-eyebrow">CLOSURE EVIDENCE</span><h4>{c.finalCheck ? 'Final inspection recorded' : 'Verification still required'}</h4><p>{c.finalCheck || 'Complete the actions and retain a conforming final inspection or verified disposition record.'}</p><span className="badge">{c.attachments.length} captured evidence file(s)</span></div><div className="execution-activity"><span className="section-eyebrow"><Clock3 size={12} />LATEST CASE ACTIVITY</span>{c.audit.slice(-3).reverse().map(e => <div key={e.id}><i /><p>{e.text}</p></div>)}</div></div>
    </div><div className="workbench-footer"><span><ShieldCheck size={13} />{c.closed ? 'Closed record retained for export.' : canClose(c) ? 'All closure conditions satisfied.' : 'Closure waits for verified execution.'}</span><div>{canClose(c) ? <button className="button primary" onClick={onClose}>Close the non-conformance <Check size={15} /></button> : <button className="button" onClick={onExport}><ArrowDownToLine size={14} />Export case record</button>}</div></div>
  </section>;
}
